### ISSUE TITLE
Unhandled Runtime Error  AxiosError: Request failed with status code 502

### ISSUE THREAD

**Issue by Rishikeswaran-17** [PySpur-Dev/PySpur#52] opened 2024-12-18 04:24 UTC
after composed and opening the host the runtime error occurs 
![Screenshot 2024-12-18 095410](https://github.com/user-attachments/assets/2f408c64-1fd6-4dd8-9cb6-1f133cb5bc31)

**Comment by srijanpatel** [comment] 2024-12-18 04:36
Hey @Rishikeswaran-17 thank you for reporting this issue. Can you share the docker logs here as well?

**Comment by Shubham-Khichi** [comment] 2024-12-18 17:34
@srijanpatel Im getting the same error here are the on pyspur-nginx-1 logs. 

2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fcore%2Fsettle.js&methodName=settle&arguments=&lineNumber=24&column=12 HTTP/1.1" 200 474 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fcore%2FAxios.js&methodName=Axios.request&arguments=&lineNumber=57&column=41 HTTP/1.1" 200 463 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fadapters%2Fxhr.js&methodName=XMLHttpRequest.onloadend&arguments=&lineNumber=73&column=66 HTTP/1.1" 200 380 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fcore%2FAxios.js&methodName=Axios.request&arguments=&lineNumber=57&column=41 HTTP/1.1" 200 463 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fadapters%2Fxhr.js&methodName=XMLHttpRequest.onloadend&arguments=&lineNumber=73&column=66 HTTP/1.1" 200 380 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
2024-12-18 11:32:10 nginx-1     | 172.20.0.1 - pyspur [18/Dec/2024:17:32:10 +0000] "GET /__nextjs_original-stack-frame?isServer=false&isEdgeServer=false&isAppDirectory=false&errorMessage=AxiosError%3A+Request+failed+with+status+code+422&file=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fcore%2Fsettle.js&methodName=settle&arguments=&lineNumber=24&column=12 HTTP/1.1" 200 474 "http://localhost:6080/workflows/S2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"

**Comment by srijanpatel** [comment] 2024-12-18 18:22
@Shubham-Khichi could you also share `pyspur-backend-1` container's logs along with the steps to reproduce this?

Here's what I tried on an ubuntu instance that worked for me:
1. clone the repo to `~/pyspur`
2. run `sudo docker compose up --build`
3. open `http://localhost:6080` in my browser, and enter the username/password given in the README
4. add my `OPENAI_API_KEY` key using the settings modal on the top right corner of the home/dashboard page
5. create a new spur with one `SingleLLMCallNode` node that uses `GPT-4o`
6. run it

It would help me a lot in resolving this issue for you if you could share details like above along with the workflow (you can download this from the header in the workflow view, or from the dashboard as well)

Here's the workflow that i just ran successfully
[New_Spur_18_12_2024,_13_12_15.json](https://github.com/user-attachments/files/18187312/New_Spur_18_12_2024._13_12_15.json)

**Comment by Shubham-Khichi** [comment] 2024-12-18 18:30
So I did exactly the same as steps 1-4 and while creating a new spur here is my diagram 
![image](https://github.com/user-attachments/assets/eec2f753-adee-44fe-a8eb-adae91d183ae)

After creating the first 2 nodes I created an input node_1 and right after that I got the error. 

To recreate it I made sure to shut down the contain and restart it -- Same issue. 
I even reinstalled a fresh instance of pyspur -- same issue. 


Here is my json :
[New Spur Dec 18 2024 11 29 AM.json](https://github.com/user-attachments/files/18187409/New.Spur.Dec.18.2024.11.29.AM.json)


hope that helps

**Comment by srijanpatel** [comment] 2024-12-18 18:50
Thanks @Shubham-Khichi this is super helpful. I believe I identified the issue and have rolled out a fix for it.

The problem is that pyspur workflows (spurs) can have only on Input and Output node. The second input node caused the issue here. I understand that this is not made clear anywhere in the product, and we will address this soon. But, as an immediate fix, I have disabled the option to add Input/Output nodes to the canvas. (because adding these nodes can break the w/f)

Now coming back to your workflow, can you try again? You can pull the latest changes from the main branch and simply import the workflow json you shared above from the dashboard view. 

Let me know if this resolves it.

**Comment by Shubham-Khichi** [comment] 2024-12-18 18:53
Will check it out shortly

**Comment by doobidoo** [comment] 2024-12-18 21:05
I ran into the same issue, and did some research. In my environement (WIN11) I checked the "pyspur-backend-1" and discovered that it repeatedly tried to restart due to the following error:
```
2024-12-18 21:48:16 /pyspur/entrypoint.sh: line 2: $'\r': command not found
2024-12-18 21:48:16 /pyspur/entrypoint.sh: line 5: syntax error near unexpected token `$'{\r''
```
This is so ridiculous!
**The error you're seeing suggests that the entrypoint.sh script in your Docker container has been saved with Windows-style line endings (\r\n) instead of Unix-style line endings (\n). This can cause problems when the script is executed in a Unix/Linux-based environment like Docker.**
Hence, I opened the file in NP++ and replaced accordingly....  "pyspur-backend-1" restarted.... **problem solved.**

**Comment by srijanpatel** [comment] 2024-12-18 21:24
Hey @doobidoo , this is very strange. `backend/entrypoint.sh` file on the main branch doesn't seem to have Windows-style line endings. That said, we haven't tested this on a windows machine yet. Doing that now. Thanks for flagging this!

**Comment by srijanpatel** [comment] 2024-12-24 19:50
Closing this issue for now. Please feel free to reopen if this occurs again on Linux systems. 
Full support for windows and updating the documentation for it is a larger issue which we'll take up separately.

**Closed by srijanpatel** 2024-12-24 19:50 UTC
Labels: bug
